keys:
  - &mactone age19yfzc8yruru3wzzz5h47u3q24x4tumr9f5my7z4vxmrlm8g52v3qcvt0h0
  - &mactoncino age1jyudkqkm6qpjhm6phwk0h0dp0n330kt6sfz4g542hmje0nz9qyvqh64h7y

creation_rules:
  - path_regex: ^secrets/.*\.yaml$
    key_groups:
      - age:
          - *mactone
          - *mactoncino
