local colors = {
	wallpaper = "{{image}}",
	background = "{{colors.background.default.hex | lighten: -2.5}}",
	foreground = "{{colors.on_background.default.hex}}",
	color0 = "{{colors.surface_bright.default.hex}}",
	color1 = "{{colors.primary.default.hex | lighten: -12.5}}",
	color2 = "{{colors.primary.default.hex | lighten: -10.0}}",
	color3 = "{{colors.primary.default.hex | lighten: -7.5}}",
	color4 = "{{colors.primary.default.hex | lighten: -5.0}}",
	color5 = "{{colors.primary.default.hex | lighten: -2.5}}",
	color6 = "{{colors.primary.default.hex | lighten: 0.0}}",
	color7 = "{{colors.on_surface_variant.default.hex}}",
	color8 = "{{colors.surface_variant.default.hex}}",
	color9 = "{{colors.primary_fixed.default.hex | lighten: -12.5}}",
	color10 = "{{colors.primary_fixed.default.hex | lighten: -10.0}}",
	color11 = "{{colors.primary_fixed.default.hex | lighten: -7.5}}",
	color12 = "{{colors.primary_fixed.default.hex | lighten: -5.0}}",
	color13 = "{{colors.primary_fixed.default.hex | lighten: -2.5}}",
	color14 = "{{colors.primary_fixed.default.hex | lighten: 0.0}}",
	color15 = "{{colors.on_surface.default.hex}}",
	primary = "{{colors.primary.default.hex}}",
	secondary = "{{colors.secondary.default.hex}}",
	tertiary = "{{colors.tertiary.default.hex}}",
	surface = "{{colors.surface.default.hex}}",
	surface_bright = "{{colors.surface_bright.default.hex}}",
	error = "{{colors.error.default.hex | lighten: -20.0}}",
}
return colors
