{ pkgs, ... }:

{
  home.packages = [
    (pkgs.writeShellScriptBin "tgtheme" ''
      # tgtheme - package a telegram-desktop theme from a colors file and a background
      #
      # a .tdesktop-theme is just a zip archive containing a colors definition file
      # and (optionally) a background image named "background.jpg". this script takes
      # the colors file generated by matugen and bundles it together with the current
      # wallpaper into a complete theme.

      cachedir="''${XDG_CACHE_HOME:-$HOME/.cache}/telegram"
      colors_default="$cachedir/colors.tdesktop-theme"
      walfile="''${XDG_CACHE_HOME:-$HOME/.cache}/wal/wal"
      outname="wal.tdesktop-theme"
      resize="1920x1080"
      blur_radius="0x16"

      msg()  { [ "$quiet" -eq 1 ] || printf " \033[1;34m::\033[0m %s\n" "$@"; }
      error() { printf " \033[1;31m::\033[0m %s\n" "$@" >&2; exit 1; }

      usage() {
      	cat <<EOF
      Usage: tgtheme [-i image] [-c colors] [-o output] [-r WxH] [-Bs] [-q] [-h]

      Bundle a colors.tdesktop-theme file and a background image into a
      .tdesktop-theme archive that telegram-desktop can import.

      Options:
        -i image    background image path (default: read from $walfile)
        -c colors   colors file (default: $colors_default)
        -o output   output .tdesktop-theme path (default: $cachedir/$outname)
        -r WxH      resize the image (default: $resize; pass "original" to skip)
        -b radius   gaussian blur radius, e.g. "0x16" (implies blur; see -B)
        -B          blur the background using the default radius ($blur_radius)
        -s hex      solid color mode: ignore the image and use a flat #rrggbb swatch
        -q          quiet (suppress status messages)
        -h          show this help
      EOF
      }

      main() {
      	local image="" outfile="" solid="" do_blur=0
      	quiet=0

      	while getopts ":i:c:o:r:b:Bs:qh" opt; do
      		case "$opt" in
      		i) image="$OPTARG" ;;
      		c) colors_default="$OPTARG" ;;
      		o) outfile="$OPTARG" ;;
      		r) resize="$OPTARG" ;;
      		b) do_blur=1; blur_radius="$OPTARG" ;;
      		B) do_blur=1 ;;
      		s) solid="$OPTARG" ;;
      		q) quiet=1 ;;
      		h) usage; exit 0 ;;
      		:) error "'-$OPTARG' requires an argument" ;;
      		\?) error "invalid option: '-$OPTARG'" ;;
      		esac
      	done

      	[ ! -f "$colors_default" ] && error "colors file not found: $colors_default"

      	outfile="''${outfile:-$cachedir/$outname}"
      	mkdir -p "$(dirname "$outfile")" || error "cannot create output directory"

      	local tempdir
      	tempdir="$(mktemp -d)"
      	trap 'rm -rf "$tempdir"' EXIT INT TERM

      	cp -f "$colors_default" "$tempdir/colors.tdesktop-theme"

      	if [ -n "$solid" ]; then
      		printf '%s' "$solid" | grep -Eq '^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$' \
      			|| error "not a valid color code: $solid"
      		msg "solid background: $solid"
      		${pkgs.imagemagick}/bin/magick convert -size 256x256 "xc:$solid" "$tempdir/background.jpg" 2>/dev/null
      	else
      		# resolve image: explicit arg, else the wal wallpaper-path file
      		if [ -z "$image" ] && [ -f "$walfile" ]; then
      			read -r image <"$walfile"
      		fi
      		[ -z "$image" ] && error "no background image (pass -i or populate $walfile)"
      		[ ! -f "$image" ] && error "image not found: $image"

      		case "$(${pkgs.file}/bin/file -b --mime-type "$image")" in
      		image/*) ;;
      		*) error "not an image: $image" ;;
      		esac
      		image="$(readlink -f "$image")"

      		local conv_args=()
      		[ "$resize" != "original" ] && conv_args+=(-resize "$resize")
      		[ "$do_blur" -eq 1 ] && conv_args+=(-blur "$blur_radius")
      		${pkgs.imagemagick}/bin/magick convert "''${conv_args[@]}" "$image" "$tempdir/background.jpg" 2>/dev/null \
      			|| error "image conversion failed"

      		msg "background: $(basename "$image")''${do_blur:+ (blurred)}"
      	fi

      	# syncing entries (zip -FS) into an existing archive is faster than
      	# recreating it; fall back to a clean archive if the sync fails.
      	if ${pkgs.zip}/bin/zip -j -FS "$outfile" "$tempdir"/* >/dev/null 2>&1; then
      		:
      	else
      		rm -f "$outfile"
      		${pkgs.zip}/bin/zip -jq "$outfile" "$tempdir"/* >/dev/null 2>&1 \
      			|| error "failed to create theme archive"
      	fi

      	msg "theme generated: $outfile"
      }

      main "$@"
    '')
  ];
}
