{
  imports = [
    ./1password.nix
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./cachix.nix
    ./containers.nix
    ./fonts.nix
    ./git.nix
    ./hyprland.nix
    ./kanata.nix
    ./locale.nix
    ./network.nix
    ./nh.nix
    ./nix.nix
    ./openvpn.nix
    ./overlays.nix
    ./packages.nix
    ./polkit.nix
    ./power.nix
    ./shell.nix
    ./tailscale.nix
    ./udev.nix
    ./virtualization.nix
  ];
}
