{
  imports = [
    ./1password.nix
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./cachix.nix
    ./fonts.nix
    ./hyprland.nix
    ./kanata.nix
    ./locale.nix
    ./network.nix
    ./nix.nix
    ./overlays.nix
    ./packages.nix
    ./shell.nix
    ./tailscale.nix
  ];
}
