# include                         colors.conf   # matugen-generated (Phase 2)

allow_remote_control            yes
listen_on                       unix:/tmp/kitty

# Font
font_size                       17

# Terminal bell
enable_audio_bell               no

# Can set 4 values for top, right, bottom and left.
window_padding_width            14
hide_window_decorations         yes
confirm_os_window_close         0

# Cursor
# shell_integration               no-cursor
cursor_blink_interval           0.6 ease-in-out
cursor_stop_blinking_after      15.0
cursor_beam_thickness           1.5
cursor_underline_thickness      2.0
cursor_trail                    1
cursor_trail_decay              0.05 0.1
cursor_trail_start_threshold    0

# Misc
update_check_interval           0
clipboard_control               write-clipboard write-primary read-clipboard read-primary

# Force Kitty to send raw xterm escape sequences for Ctrl+Shift+HJKL
map ctrl+shift+h send_text all \x1b[72;5u
map ctrl+shift+j send_text all \x1b[74;5u
map ctrl+shift+k send_text all \x1b[75;5u
map ctrl+shift+l send_text all \x1b[76;5u
