{ pkgs, config, lib, ... }:

{
  # --- GTK ----------------------------------------------------------------
  # The gtk.css/colors.css files are NOT shipped here — matugen regenerates
  # them on wallpaper change (see matugen.nix). This module only writes
  # settings.ini (theme/icon/cursor/font), which is stable across recolors.
  gtk = {
    enable = true;

    theme = {
      name = "adw-gtk3-dark";
      package = pkgs.adw-gtk3;
    };

    iconTheme = {
      name = "Papirus-Dark";
      package = pkgs.papirus-icon-theme;
    };

    cursorTheme = {
      name = "Bibata-Modern-Classic";
      package = pkgs.bibata-cursors;
    };

    font = {
      name = "Sans 14";
      package = pkgs.poppins;
    };
  };

  # --- Cursor -------------------------------------------------------------
  # Sets XCURSOR_THEME/SIZE for Wayland/X11 apps and the GTK cursor config.
  # bibata only ships xcursor format (no hyprcursor), so Hyprland itself is
  # told about it via `hyprctl setcursor` in hypr/source/appearence.lua.
  home.pointerCursor = {
    package = pkgs.bibata-cursors;
    name = "Bibata-Modern-Classic";
    size = 24;
    gtk.enable = true;
    x11.enable = true;
  };

  # --- Qt5ct / Qt6ct ------------------------------------------------------
  # QT_QPA_PLATFORMTHEME=qt5ct is set in hypr/source/env.lua. The palettes
  # (colors/matugen.conf) are regenerated by matugen; we only ship the static
  # .conf, with its hardcoded /home/xitonight path repointed at XDG_CONFIG_HOME.
  xdg.configFile."qt5ct/qt5ct.conf".text =
    lib.replaceStrings [ "/home/xitonight/.config" ]
    [ "${config.xdg.configHome}" ] (builtins.readFile ./qt5ct.conf);

  xdg.configFile."qt6ct/qt6ct.conf".text =
    lib.replaceStrings [ "/home/xitonight/.config" ]
    [ "${config.xdg.configHome}" ] (builtins.readFile ./qt6ct.conf);

  home.packages = with pkgs; [
    papirus-icon-theme
    libsForQt5.qt5ct
    qt6Packages.qt6ct
    libsForQt5.qtwayland
    qt6.qtwayland
    nwg-look
  ];
}
