{ pkgs, ... }:

{
  # rofi-emoji is a compiled rofi plugin (emoji.so), so rofi must be wrapped
  # with it. rofi-rbw is a standalone binary invoked as a rofi mode. The colors
  # file (shared/colors.rasi) is generated by matugen, so it is NOT shipped here
  # — rofi theming only fully resolves after `matugen image` runs once.
  home.packages =
    [ (pkgs.rofi.override { plugins = [ pkgs.rofi-emoji ]; }) pkgs.rofi-rbw ];

  xdg.configFile = {
    "rofi/config.rasi".source = ./rofi/config.rasi;
    "rofi/run.rasi".source = ./rofi/run.rasi;
    "rofi/window.rasi".source = ./rofi/window.rasi;
    "rofi/clipboard.rasi".source = ./rofi/clipboard.rasi;
    "rofi/wallpaper.rasi".source = ./rofi/wallpaper.rasi;
    "rofi/emoji.rasi".source = ./rofi/emoji.rasi;
    "rofi/shared/defaults.rasi".source = ./rofi/shared/defaults.rasi;
  };
}
